# Generated by Django 2.2 on 2019-04-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0006_auto_20190427_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='post',
            name='map_data',
            field=models.URLField(blank=True, max_length=900, verbose_name='URL на карте'),
        ),
        migrations.AlterField(
            model_name='post',
            name='more_text',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='post',
            name='website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Сайт'),
        ),
    ]
