# Generated by Django 2.2 on 2019-04-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0007_auto_20190427_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='map_data',
            field=models.TextField(blank=True, verbose_name='URL на карте'),
        ),
    ]
