# Generated by Django 2.2 on 2019-04-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0008_auto_20190427_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('a', 'Классическая архитектура'), ('b', 'Современная архитектура'), ('c', 'Скульптура'), ('d', 'Музеи, выставки и галереи'), ('e', 'Театры'), ('f', 'Улицы, площади'), ('g', 'Природные объекты'), ('h', 'Развлечения')], max_length=1, verbose_name='Вид'),
        ),
    ]
